"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import SocketProvider from "@/context/SocketProvider";
import { QueryClient, QueryClientProvider } from "react-query";
const inter = Inter({ subsets: ["latin"] });
import "../i18n/i18n";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <AuthProvider>
          <SocketProvider>
            <QueryClientProvider client={queryClient}>
              {children}
            </QueryClientProvider>
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
